<?php
return [
    'FCM_SERVER_KEY' => 'AAAAyk7Zr1k:APA91bF6zj7W4xCBWGVbvfZvHvLEY50vij9zQhe-KmlpztEwOPX-4fUbGKpXfvZSScBa3GVE98vX5lKjy0FmG5RBRfOx5Xtemd7A_k5JxRifBkA148Lpizh0W8jyqqg08ZkflVDgkPSW',
    'admin_profile_img_path' => 'public/uploads/admin/profile_image',
    'user_profile_img_path' => 'public/uploads/user/profile_image',
    'user_project_path' => 'public/uploads/user/project',
    'donation_file_upload_path' => 'public/uploads/user/donation',
    'community_file_upload_path' => 'public/uploads/user/community',
    'no_image_path' => 'public/uploads/image/no_image.png',
    'no_user_image_path' => 'public/uploads/image/profile-img.png',
    'admin_mail' => env('ADMIN_EMAIL','admin1@yopmail.com'),
    'esg_path'  => '/app/esg_report/',
    'subscription_path'  => '/app/subscription/',
    'esg_type'  => 'esg',
    'subscription_type'  => 'subscription',
    'to_donation_limit' => 5,
    'project_report_path'  => '/app/project_report/',
    'project_type'  => 'project',
    'common_not_at_all'  => 'Not at all',
    'common_rarely'  => 'Rarely',
    'common_regular'  => 'Regular',
    'user_type'  => 'user',
    'user_path'  => '/app/user_report/',
    'completed_by_owner' => 'Completed by Owner',
    'currency' => 'USD',
    'paid_status' => 'Paid',
    'donation' => 1,
    'volunteer' => 2,
    'status_goal_reach' => 'Goal Reached',
    'acct_enc_key'=>'zXDMR3riZ37sCRcjeRh5HycJ3PwBW6uI',
    'encryption_method' => 'aes-128-ecb'
];
