<?php

return [
    'common_message' => [
        'exception_error' => 'Something went wrong.',
        'success_message' => 'Data found.',
        'error_message' => 'No data found.',
        'no_data_found' => 'No data found',
        'success_delete' => 'Data deleted successfully.',
        'file_not_upload' => 'No file uploaded.',
        'can_not_delete_record' => 'You cannot delete this record. Reference element already associated with other records.'
    ],
    'candidate_message' => [
        'status_changed_successfully' => 'Status changed successfully.',
        'job_applicant_not_found' => 'Job applicant not found.',
        'invitation_sent_successfully' => 'Invitation sent successfully.',
        'sorry_please_try_again_later' => 'Sorry! Please try again later.',
        'search_candidates' => 'Search Candidates.',
        'notification_sent_successfully' => 'Notification sent successfully.',
        'candidate_register' =>  'You are registered successfully. You will receive verification link on registered email id.',
        'candidate_education_added' => 'Education data added successfully.',
        'candidate_skill_added' => 'Skill data added successfully.',
        'candidate_profile_added' => 'Candidate data updated successfully.',
        'candidate_experiences_added' => 'Experience data added successfully.',
        'candidate_not_found' => 'Candidate not found.',
        'resume_upload_successfully' => 'Resume uploaded successfully.',
        'resume_already_uploaded' => 'Resume already uploaded.',
        'delete_education_success' => 'Education data deleted successfully.',
        'delete_skill_success' => 'Skill data deleted successfully.',
        'delete_experience_success' => 'Experience data deleted successfully.',
        'bookmark_added_success' => 'Bookmark data added successfully.',
        'bookmark_already_added' => 'This job has already been bookmarked.',
        'delete_bookmark' => 'Bookmark data deleted successfully.'
    ],
    'job_message' => [
        'job_already_posted' => 'Job already posted.',
        'job_posted_successfully' => 'Job posted successfully.',
        'job_reactivated_successfully' => 'Job reactivated successfully.',
        'job_already_activated' => 'Job already activated.',
        'location_data_not_found_for_this_job' => 'Location data not found for this job.',
        'hired_candidates_count_saved_successfully' => 'Hired candidates count saved successfully.',
        'job_not_found' => 'Job not found.',
        'job_already_applied' => 'You have already applied for this job.',
        'job_applied_successfully' => 'You have applied job successfully.',
        'find_jobs' => 'Find Jobs.',
        'job_status_updated' => 'Job status updated successfully.',
        'job_already_requested' => 'You have already requested for this job.',
        'candidate_job_already_applied' => 'Candidate has already applied for this job.'
    ],
    'employer_message' => [
        'general_setting_added_successfully' => 'Employer general setting added successfully.',
        'employer_profile_added' => 'Company profile updated successfully.',
    ],
    'auth_message' => [
        'invalid_token' => 'Your session has expired. Please login again to continue working',
        // 'invalid_token' => 'Token is invalid',
        'token_not_found' => 'User not found',
        // 'token_not_found' => 'Token not found',
        'token_expired' => 'Your session has expired. Please login again to continue working.',
        'user_not_found_with_given_email' => 'User not found with given email.',
        'given_credentials_are_invalid' =>  'Given credentials are invalid.',
        'token_could_not_create' => 'Token could not create.',
        'user_logged_in_successfully' => 'User logged in successfully.',
        'user_successfully_signed_out' => 'User successfully signed out.',
        'user_not_found' => 'User not found.',
        'register_employer_success' =>  'You are registered successfully. You will receive verification link on registered email id.',
        'mail_sent_succesfully_for_reset_password' =>  'Mail sent succesfully for reset password.',
        'password_reset_successfully' => 'Password reset successfully.',
        'email_already_verified' =>  'Email already verified.',
        'email_verified_successfully' => 'Email verified successfully.',
        'token_found_successfully' =>  'Token found successfully.',
        'password_changed_successfully' => 'Password changed successfully.',
        'wrong_password_error' => 'Old Password is incorrect.',
        'password_compare_error' =>  'New Password cannot be same as your current password.',
        'verify_email' => 'Please verify an email first before login.',
        'admin_user_not_found' => 'Admin user not found.',
        'admin_user_not_found_with_given_email' => 'Admin user not found with given email.',
        'please_login_again_with_new_password' => 'Please login again with new password.',
        'admin_inactive' => 'Your account is inactive please contact to admin.',
        'refresh_token_successfully' => 'Token refresh successfully.',
    ],
    'admin_users' => [
        'admin_users_fetched_successfully' => 'Admin user fetched successfully.',
        'admin_user_created_successfully' => 'Admin user created successfully, please check email for login credentials.',
        // 'admin_user_created_successfully' => 'Admin user created successfully.',
        'admin_user_not_found' => 'Admin user not found.',
        'admin_user_updated_successfully' => 'Admin user updated successfully.',
        'admin_user_deleted_successfully' => 'Admin user deleted successfully.',
        'user_groups_fetch_success' => 'User groups fetched successfully.'
    ],
    'user_group_admin' => [
        'userGroups_fetched_successfully' => 'UserGroups fetched successfully.',
        'userGroups_created_successfully' => 'UserGroups created successfully.',
        'userGroup_fetched_successfully' => 'UserGroup fetched successfully.',
        'userGroup_not_found' => 'UserGroup not found.',
        'userGroup_updated_successfully' => 'UserGroup updated successfully',
        'userGroup_deleted_successfully' => 'UserGroup deleted successfully.'
    ],
    'utility_admin' => [
        'menus_get_succesfully' => 'Menus get succesfully.',
        'permission_denied_for_this_operation' => 'Permission denied for this operation.',
        'permission_granted' => 'Permission granted.',
        'not_found_any_permission' => 'Not found any permission.',
        'contact_super_user' => 'Not found any permission for this user group, So please contact with super user.'
    ],
    'admin_email_template' => [
        'email_template_created_successfully' => 'Email template created successfully.',
        'email_template_not_found' => 'Email template not found.',
        'email_template_updated_successfully' => 'Email template updated successfully.',
        'email_templates_deleted_successfully' => 'Email templates deleted successfully.'
    ],
    'admin_experiences' => [
        'experiences_already_exits' => 'Experiences already exits.',
        'experiences_created_successfully' => 'Experiences created successfully.',
        'experiences_updated_successfully' => 'Experiences updated successfully.',
        'experiences_not_found' => 'Experiences not found.',
        'experiences_deleted_successfully' => 'Experiences deleted successfully.'
    ],
    'acl_checker' => [
        'not_found_any_permission' => 'Not found any permission.',
        'add_action_module_and_type_header' => 'Please add action-module and action-type header in request header.',
        'permission_denied_for_this_operation' =>  'Permission denied for this operation.',
        'not_found_permission_contact_super_user' => 'Not found any permission for this user group, So please contact with Super user.'
    ],
    'admin_profile' => [
        'fetched_success' => 'Profile fetched successfully.',
        'email_exist' => 'Email already exist.',
        'update_success' => 'Profile updated successfully.',
    ],
    'admin_template_management' => [
        'added_success' => 'Template added successfully.',
        'updated_success' => 'Template updated successfully.',
        'not_found' => 'Template not found.',
        'fetch_success' => 'Template details fetched successfully.',
        'delete_success' => 'Template deleted successfully.',
    ],
    'admin_cms_management' => [
        'added_success' => 'CMS added successfully.',
        'updated_success' => 'CMS updated successfully.',
        'not_found' => 'CMS not found.',
        'fetch_success' => 'CMS details fetched successfully.',
        'delete_success' => 'CMS deleted successfully.',
        'cms_page_fetch_successfully' => 'CMS page fetched successfully.',
        'cms_page_not_fetch' => 'CMS page not fetched.',
    ],
    'admin_site_settings' => [
        'add_success' => 'Site settings added successfully.',
        'update_success' => 'Site settings updated successfully.',
        'not_found' => 'Site settings not found.',
        'fetch_success' => 'Site settings fetched successfully.',
    ],
    'admin_users_management' => [
        'fetch_success' => 'Users fetched successfully.',
        'not_found' => 'User not found.',
        'user_detail_fetch_success' => 'User details fetched successfully.',
    ],
    'admin_feedback' => [
        'fetch_success' => 'Feedbacks fetched successfully.',
        'not_found' => 'Feedback not found.',
        'delete_success' => 'Feedback deleted successfully.',
    ],
    'admin_project' => [
        'fetch_success' => 'Projects fetched successfully.',
        'not_found' => 'Projects not found.',
        'delete_success' => 'Project deleted successfully.',
        'users_fetch_success' => 'Project users fetch successfully.',
        'project_approved' => 'Project approved successfully.',
        'project_rejected' => 'Project rejected successfully.',
        'project_report_fetched_success' => 'Project report list fetched successfully.',
    ],
    'admin_esg_report' => [
        'fetch_success' => 'ESG reports fetched successfully.',
        'not_found' => 'ESG reports not found.',
        'delete_success' => 'ESG report deleted successfully.'
    ],
    'admin_subscription' => [
        'fetch_success' => 'Subscriptions fetched successfully.',
        'not_found' => 'Subscriptions not found.',
        'delete_success' => 'Subscription deleted successfully.'
    ],
    'transactions' => [
        'fetch_success' => 'Transactions fetched successfully.',
        'users_fetch_success' => 'Transaction users fetch successfully.',
    ],

    //front users
    'front_user' => [
        'registered_success' => 'User register successfully. Please verify your email.',
        'user_email_not_verify' => 'You need to confirm your account. We have sent you an activation code, please check your email.',
        'user_email_verify_successfully' => 'Your email is verified.',
        'user_email_already_verfify' => 'Your email is already verified.',
        'in_valid_verify_token' => "In valid verify token.",
        'user_not_found' => 'User not found.',
        'user_details_success' => 'User details added successfully.',
        'user_details_update_success' => 'User details updated successfully.',
        'user_details_email_err' => 'User email already exist.',

        'follow_success' => 'Follow successfully.',
        'unfollow_success' => 'Unfollow successfully.',
        'auth_user_not_found' => 'User not found with given email.',
        'auth_mail_sent_succes' =>  'Mail sent succesfully for reset password.',
        'auth_password_reset_success' => 'User Password reset successfully.',
        'auth_wrong_password_error' => 'Old Password is incorrect.',
        'auth_password_compare_error' =>  'New Password cannot be same as your current password.',
        'auth_change_pwd_success' => 'Please login again with new password.',
        'user_profile_fetched_success' => 'User profile fetched successfully.',
        'user_profile_email_exist' => 'Email already exist.',
        'user_profile_update_success' => 'User profile updated successfully.',
        'user_details_fetch_success' => 'User details fetched successfully.',
        'project_not_found' => 'Project not found.',
        'project_detail_fetch_success' => 'Project details fetched successfully.',
        'project_added_success' => 'Project added successfully.',
        'project_updated_success' => 'Project updated successfully.',
        'project_submit_success' => 'Project submitted successfully.',
        'projects_fetch_success' => 'Projects fetched successfully.',
        'projects_not_available' => 'No projects available.',
        'project_delete_success' => 'Project deleted successfully.',
        'project_docs_add_success' => 'Project document added successfully.',
        'project_cover_image_add_success' => 'Project Cover image uploaded successfully.',
        'project_doc_not_found' => 'Project document not found.',
        'project_doc_delete_success' => 'Project document deleted successfully.',
        'project_cover_image_delete_success' => 'Project cover image deleted successfully.',
        'project_docs_not_found' => 'Project documents not found.',
        'project_docs_fetch_success' => 'Project documents fetched successfully.',
        'project_feel_good_not_found' => 'Feel good data not found.',
        'project_feel_good_fetch_success' => 'Feel good data fetched successfully.',
        'project_closed_success' => 'Project Completed successfully.',
        // 'project_closed_success'=>'Project Closed successfully.',
        'project_already_added_review'=>'You have already added review.',
        'project_review_add_success'=>'Project review added successfully.',
        'user_dashboard_fetch_success'=>'User dashboard data fetched successfully.',
        'user_dashboard_fetch_failure'=>'Data not found.',
        'follow_data_not_found'=>'You are not following any projects.',
        'esg_report_email_add_success'=>'Email is registered successfully for esg reports.',
        'volunteer_add_success'=>'Volunteer added successfully.',
        'donation_add_successfuly'=>'Donation added successfully.',
        'community_post_add_successfuly'=>'Post added successfully.',
        'comment_add_success'=> 'Comment added successfully.',
        'community_data_not_found'=> 'Nodata.',
        'like_success' => 'Post like added successfully.',
        'community_already_like' => 'Post already like.',
        'unlike_success' => 'Post unlike successfully.',
        'donation_data_not_found' => 'Donation details not found',
        'donation_recurring_stop' => 'Donation recurring stop successfully',
    ],

    'general_msg' => [
        'categories_fetch_success' => 'Categories fetched successfully.',
        'sdgs_fetch_success' => 'Sdgs fetched successfully.',
        'category_fetch_success' => 'Category fetched successfully.',
        'countries_fetch_success' => 'countries fetched successfully.',
        'industries_fetch_success' => 'Industries fetched successfully.',
    ],
    'project_email_notification' => 'Project report file export process started, you will receive an e-mail.',
    'subscription_email_notification' => 'Subscription report file export process started, you will receive an e-mail.',
    'esg_email_notification' => 'Esg report file export process started, you will receive an e-mail.',
    'user_listing_fetched_success' => 'User list fetched successfully.',
    'user_email_notification' => 'User report file export process started, you will receive an e-mail.',
];
